### ISSUE TITLE
Beat Saber 1.20+ update

### ISSUE THREAD

**Issue by pravic** [ErisApps/HitScoreVisualizer#14]
Any plans regarding it?

**Comment by ErisApps** [comment]
Hii,

Beat Saber 1.20.0 was a fairly big update because it introduced new note types, also due to HSV not being the only mod that I maintain and having other responsibilities 😅
I've released a version for Beat Saber 1.20.0 and 1.21.0 yesterday, but make sure to read the important information block on the latest release. It can be found in the releases section: https://github.com/ErisApps/HitScoreVisualizer/releases
