### ISSUE TITLE
Make judgements fully opaque

### ISSUE THREAD

**Issue by Kakifrucht** [ErisApps/HitScoreVisualizer#5]
It would be nice if Judgements could be made fully opaque. Currently the stage lighting affects the colors of your judgements slightly, which makes reading them difficult with wild Chroma powered lighting effects.

**Comment by Kakifrucht** [comment]
I can't find any specific commit that might have fixed this, but it looks like with the newest version all judgements are opague now?
I hope that was intended and whatever was changed won't be reverted.

Thanks alot!

**Comment by ErisApps** [comment]
My response was kinda late as I didn't know you had created this issue (please also let me know on Discord next time) 😅 

That being said, the change was caused by a change in how the basegame displays note cut scores since 1.13.4 and I'm planning on offering both possibilities as an option *once I've figured out a way to revert it to the old way*.

**Comment by Kakifrucht** [comment]
No problem, the solution sounds good to me!
